#cloud-config

manage_etc_hosts: "localhost"
coreos:
  update:
    reboot-strategy: "off"
  units:
  - name: var-lib-cassandra.mount
    command: start
    enable: true
    content: |
      [Unit]
      Description=Mount ephemeral-backed LVM to /var/lib/cassandra
      [Mount]
      What=/dev/data/cassandra
      Where=/var/lib/cassandra
      Type=ext4
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/entropy-source.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Provide entropy source via haveged
      [Service]
      Type=simple
      ExecStart=/usr/bin/rkt run --insecure-options image,capabilities docker://dit4c/haveged
      Restart=always
      RestartSec=30
      [Install]
      WantedBy=multi-user.target
